name: QA Deploy - Academic Forum Domain

on:
  pull_request:
    types: [closed]
    branches: [qa]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push discussion-service
        run: |
          cd uniforum-backend/academic-forum-domain/discussion-service
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/discussion-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/discussion-service:latest

      - name: Build & Push reply-service
        run: |
          cd uniforum-backend/academic-forum-domain/reply-service
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/reply-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/reply-service:latest

      - name: Desplegar en EC2 - Academic Forum Domain
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_ACADEMIC_FORUM }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker network inspect uniforum-net >/dev/null 2>&1 || sudo docker network create uniforum-net

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/discussion-service:latest
            sudo docker stop discussion-service || true && sudo docker rm discussion-service || true
            sudo docker run -d -p 8003:8003 --name discussion-service --network uniforum-net ${{ secrets.DOCKER_USERNAME }}/discussion-service:latest

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/reply-service:latest
            sudo docker stop reply-service || true && sudo docker rm reply-service || true
            sudo docker run -d -p 8004:8004 --name reply-service --network uniforum-net ${{ secrets.DOCKER_USERNAME }}/reply-service:latest
