name: QA Deploy - Analysis Domain

on:
  pull_request:
    types: [closed]
    branches: [qa]
    paths:
      - 'uniforum-backend/analysis-domain/**'
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push metrics-service
        run: |
          cd uniforum-backend/analysis-domain/metrics-service
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/metrics-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/metrics-service:latest

      - name: Build & Push heatmap-service
        run: |
          cd uniforum-backend/analysis-domain/heatmap-service
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/heatmap-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/heatmap-service:latest

      - name: Build & Push top-topic-service
        run: |
          cd uniforum-backend/analysis-domain/top-topic-service
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/top-topic-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/top-topic-service:latest

      - name: Desplegar en EC2 - Analysis Domain
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_ANALYSIS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker network inspect uniforum-net >/dev/null 2>&1 || sudo docker network create uniforum-net

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/metrics-service:latest
            sudo docker stop metrics-service || true && sudo docker rm metrics-service || true
            sudo docker run -d -p 8020:8020 --name metrics-service --network uniforum-net -e DATABASE_URL="postgres://uniforum_user:1234@18.213.7.19:5432/uniforum?sslmode=disable" ${{ secrets.DOCKER_USERNAME }}/metrics-service:latest

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/heatmap-service:latest
            sudo docker stop heatmap-service || true && sudo docker rm heatmap-service || true
            sudo docker run -d -p 8023:8023 --name heatmap-service --network uniforum-net -e DATABASE_URL="postgres://uniforum_user:1234@18.213.7.19:5432/uniforum?sslmode=disable" ${{ secrets.DOCKER_USERNAME }}/heatmap-service:latest

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/top-topic-service:latest
            sudo docker stop top-topic-service || true && sudo docker rm top-topic-service || true
            sudo docker run -d -p 8021:8021 --name top-topic-service --network uniforum-net -e DATABASE_URL=postgresql://uniforum_user:1234@18.213.7.19:5432/uniforum ${{ secrets.DOCKER_USERNAME }}/top-topic-service:latest
